### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by hydrargyrum** [kinnison/git-testament#31]
The README doesn't give an example of the output. Is it a hash? A description? In what format?

**Comment by kinnison** [comment]
Hi, this is a good point I guess I need to direct the reader of the README to the rustdoc a little more.

If you use the rustdoc then you get led to the [GitTestament](https://docs.rs/git-testament/latest/git_testament/struct.GitTestament.html) docs which explain the data structure.

Could you come up with a PR for the README which makes this clearer for new users?
